### PR TITLE
there is no need to wrap bundle

### PR DESCRIPTION
**Pull request by wenbing**

### CODE REVIEW

**Comment by joeybaker** [comment]
:+1:

**Comment by joshwnj** [comment]
Thanks @wenbing ! This is definitely a more "proper" way to use browserify :) Then only question in my mind is that previously, the `bundle` callback would only be called after the css file has finished writing. With these changes that order may be different, right?

I'm not sure if that's going to cause any issues but at this stage I'm happy to go ahead and accept this PR, and fix any issues that arise. @joshgillies can you think of any reason this shouldn't be merged?

**Comment by joshgillies** [comment]
This has bugged me for some time. Looks solid! :+1:

Merging!

**Comment by riophae** [comment]
Awesome!

**Pull request merged**
