### PR TITLE
Fix separation of loaders

### LINKED ISSUE #76: Multiple browserify instances get mixed up
Probably related to #57.

I have a bit strange setup with gulp and browserify but I would still expect the following to work:
```javascript
// build whole app
gulp.task('build', ['build-screen', 'build-remote']);

// calls browserify to compile jsx files for the screen
gulp.task('build-screen', function() {
	bundle('screen');
});

// calls browserify to compile jsx files for the remote
gulp.task('build-remote', function() {
	bundle('remote');
});

function bundle(entry) {
	return browserify({ 
		entries: entry,
		extensions: ['.jsx'],
		basedir: './src',
	})
	.plugin(modulesify, {
		rootDir: './src',
		output: './static/css/' + entry + '.css',
	})
	.transform(babelify.configure({ presets: ["es2015", "react", "stage-0"] }))
	.bundle()
	.pipe(source(entry))
	.pipe(rename({ extname: '.js' }))
	.pipe(gulp.dest('./static/js'));
}
```

Instead of doing the expected (outputting 'screen.css' and 'remote.css' with their respective contents) it dumps all the css (for both instances) in 'remote.css' and produces an empty 'screen.css'.

When using the `css stream` like so: 
```javascript
function bundle(entry) {
	return browserify({ 
		entries: entry,
		extensions: ['.jsx'],
		basedir: './src',
	})
	.plugin(modulesify, {
		rootDir: './src',
	})
	.transform(babelify.configure({ presets: ["es2015", "react", "stage-0"] }))
	.bundle()
	.on('css stream', function (css) {
		css.pipe(fs.createWriteStream( './static/css/' + entry +'.css'));
	})
	.pipe(source(entry))
	.pipe(rename({ extname: '.js' }))
	.pipe(gulp.dest('./static/js'));
```
It outputs all of the imported css to both files instead of only the relevant css.

I hope you can tell me what (if anything) I'm doing wrong :smile:

### PR DESCRIPTION
**Pull request by tjallingt**
Fixes #76 
(also included some code style fixes as suggested by the linter)

### CODE REVIEW

**Comment by huan086** [comment]
It works. Thanks!
However, for this to work, output cannot be optional, so the docs needs to updated too

    output: path to write the generated css. If not provided, you'll need to listen to the 'css stream' event on the bundle to get the output.

**Comment by joeybaker** [comment]
FWIW, output is optional so that you can get the output as a stream instead of a file. It would be great if the solution worked for both of these use-cases.

**Comment by tjallingt** [comment]
As far as I can tell it doesn't change the functionality when not given a `cssOutFilename` as it will just store the loader the same as before. This fix only changes the functionality of the code when presented with multiple different `cssOutFilename`s....

**Comment by joeybaker** [comment]
cool beans.

**Comment by joshwnj** [comment]
Thanks for these updates @tjallingt , and for being patient while I got some time to review :)

**Comment by joshwnj** [comment]
published v0.17.0

**Pull request merged**
