### PR TITLE
respect NODE_PATH env variable while resolving modules

### PR DESCRIPTION
**Pull request by anru**

### CODE REVIEW

**Comment by joshwnj** [comment]
Hi @anru , thanks for this. As I understand, `process.env.NODE_PATH` is `undefined` by default, which would break.  How do you think we should solve that?

**Comment by anru** [comment]
Oh, @joshwnj sorry, forgot about this PR. 
I added commit which fixes issue you mentioned.

**Comment by joshwnj** [comment]
thanks @anru !

**Comment by joshwnj** [comment]
published v0.26.0

**Pull request merged**
