### PR TITLE
new option and updated readme

### PR DESCRIPTION
**Pull request by joshwnj**
Although we've discussed further improvements to the plugin architecture in #26 I'd like to add this new option in the meantime, since it's completely opt-in and doesn't affect existing behaviour.

@joshgillies pls take a look and merge if you're happy with it.

### CODE REVIEW

**Comment by joshgillies** [comment]
Sorry for the delay in getting onto this!

So I worry about this. In that in terms of an API it feels sloppy. Would it be better to change how the `-u` works, to basically not nuke the default PostCSS plugins for CSS Modules?

That being said, if the goal is to eventually re-architect the way plugins are handled anyway and assuming this PR solves problems people are having currently I'd be OK to +1 this.

Would it be much effort to tack on a CLI option to set this also? `--after [pluginA, pluginB]` maybe?

**Comment by joshwnj** [comment]
Yeah, I think longer-term it would be better to change the behaviour of `-u` so that by default the css modules plugins are preserved.  Would you be happy with this as a non-breaking-change solution for now, and then aim to change `-u` when we go to 1.0?

I'll look at adding the `--after` CLI option.

**Comment by joshgillies** [comment]
Assuming we can get the CLI to feature parody with the Core API I'd be keen to release this.

Thanks for making this happen! :+1:

**Comment by joshwnj** [comment]
@joshgillies I've added `--after` for CLI, please take a look and merge if you're happy with it.

**Comment by joshgillies** [comment]
Happy days! :smile:

Merging!

**Pull request merged**
