### PR TITLE
Use browserify basedir as a fallback for rootDir

### LINKED ISSUE #75: consider Browserify basedir for rootDir
An example of a relatively common way to call browserify is this:
```
browserify({ 
	entries: "entry.js",
	basedir: './src',
})
```
Why would you have to specify the `rootDir` when it is probably the same as browserify's `basedir`?
I would suggest to have `css-modulesify` use the `rootDir` when specified, then try the `browserify._options.basedir` and only if that is also not specified use the current folder.

### PR DESCRIPTION
**Pull request by tjallingt**
fixes #75

### CODE REVIEW

**Comment by tjallingt** [comment]
Perhaps some tests for this change would be nice but I have no idea how to fit that into the current testing framework. :worried:

**Comment by tjallingt** [comment]
actually im not sure why that `options.d` is there so i should have probably put it before the `basedir`...

**Comment by joshwnj** [comment]
@tjallingt `options.d` is the shorthand of the `rootDir` argument.  Let's put it before `basedir`, and then we'll be good to merge :) Thanks!

**Comment by tjallingt** [comment]
done :smile:

**Comment by joshwnj** [comment]
Thanks @tjallingt , published v0.19.0

**Pull request merged**
