### PR TITLE
Composing from a node_module

### PR DESCRIPTION
**Pull request by joshwnj**
This is currently failing as there are some path issues.

### CODE REVIEW

**Comment by joshwnj** [comment]
The latest change introduces a new optional `rootDir` option.

Will need to submit a PR to css-modules-loader-core before we can merge this.

**Comment by joshwnj** [comment]
hey @joshgillies, I'd appreciate your feedback on this. If all looks good please go ahead and merge

**Comment by joshgillies** [comment]
Looks good! And great work with getting tests in :+1:

**Comment by joshwnj** [comment]
Cheers!

**Pull request merged**
