### PR TITLE
fix: allow users to override generateScopedName

### PR DESCRIPTION
**Pull request by joeybaker**
b/c sometimes, the default doesn’t work out!

### CODE REVIEW

**Comment by joshgillies** [comment]
> b/c sometimes, the default doesn’t work out!

Can you elaborate on what's meant by doesn't work out? An example case would be great! :+1:

**Comment by joeybaker** [comment]
Of course. Sorry for being non-obvious. Here's what I'm trying to do:

```js
const cssModulesifyOptions = {
  output: cssOutputPath
  , use: cssModulesCore.defaultModules.concat([
    postCssCustomProperies({
      variables
    })
    , autoprefixer({
      browsers: '> 5%'
    })
  ]
  , 'postcss-modules-scope': {
    // this doesn't work because my custom function will be over-ridden without this patch.
    generateScopedName: (className, path, css) => {
      return // my custom className
    }
  }
}

```

**Comment by joshgillies** [comment]
Happy days! Thanks for the PR :+1:

**Comment by joshwnj** [comment]
Thanks @joeybaker !

**Pull request merged**
